version: '3.8'

services:
  postgres:
    container_name: bug-tracker-postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tracker
    volumes:
      - ./postgreSQL/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

