version: '3.8'

services:

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - postgres
        - backend

  backend:
      build:
        context: ./express
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      environment: 
        - DB_USER=${POSTGRES_USER}
        - DB_HOST=bug-tracker-postgres
        - DB_NAME=tracker
        - DB_PASSWORD=${POSTGRES_PASSWORD}
        - DB_PORT=5432
      depends_on:
        - postgres

  postgres:
    container_name: bug-tracker-postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tracker
    volumes:
      - ./postgreSQL/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

